version: '3.9'
networks:
  algafood-network:
    driver: bridge
services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "3307:3306"
    networks:
      - algafood-network

  algafood-api:
    image: aldeir5050/alga-food-api
    environment:
      DB_HOST: algafood-mysql
    ports:
      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql
  