version: '3.9'
networks:
  algafood-network:
    driver: bridge
services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "12345"
    ports:
      - "3307:3306"
    networks:
      - algafood-network

  algafood-redis:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network

  algafood-api:
    image: aldeir5050/alga-food-api
    # command: ["/wait-for-it.sh", "algafood-mysql:3307", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql
  
  